### ISSUE TITLE
kubectl apply artifacts/operator-amd64.yaml

### ISSUE THREAD

**Issue by paul931224** [openfaas-incubator/ingress-operator#25]
## Expected Behaviour

It should deploy the operator

## Current Behaviour

The deployment never gets ready, CrashLoopBack on pod

## Possible Solution

Modify ingress-operator/artifacts/operator-amd64.yaml

command:
          - ./ingress-operator
          - -logtostderr
          - -v=2

remove --v=2
After that it worked for me.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`

1.6

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Fixed by: 0f12b7b
