### ISSUE TITLE
kubectl apply artifacts/operator-rbac.yaml

### ISSUE THREAD

**Issue by paul931224** [openfaas-incubator/ingress-operator#26]
## Expected Behaviour

It should deploy artifacts/operator-rbac.yaml

## Current Behaviour

It deploys, but `kubectl logs ` come back with
```Failed to list *v1beta1.Ingress: ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:openfaas:ingress-operator" cannot list resource "ingresses" in API group "networking.k8s.io" in the namespace "openfaas"```

## Possible Solution

modify artifacts/operator-rbac.yaml

- apiGroups: ["extensions", "networking"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

to

- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

## Context
Trying to setup custom domain for my functions
## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
1.6
* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel

**Comment by alexellis** [comment]
Fixed by: 0f12b7b
