### ISSUE TITLE
Update readme and examples to show path is required

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas-incubator/ingress-operator#37]
## Expected Behaviour

```sh
$ kubectl apply -f examples/tls-nodeinfo-ingress.yaml
functioningress.openfaas.com/nodeinfo-tls created
```

## Current Behaviour

```sh
$ kubectl apply -f examples/tls-nodeinfo-ingress.yaml
The FunctionIngress "nodeinfo-tls" is invalid: spec.path: Required value
```

## Possible Solution

Add `path: "/"` to each of the examples and remove the comment in the Readme that `path` is optional https://github.com/openfaas-incubator/ingress-operator#schema

## Context

Trying to test my last PR by using the example files

**Comment by alexellis** [comment]
This is regression in the generated CRD, it should still be optional. I had similar in the Inlets Operator but found a way to fix it with labels for the CRD generator.

https://github.com/inlets/inlets-operator/blob/master/pkg/apis/inletsoperator/v1alpha1/types.go

It might have just been adding // +optional

**Comment by LucasRoesler** [comment]
The spec hasn't changed in months, so I am not sure it was ever actually optional

**Comment by alexellis** [comment]
It's not the spec, but the CRD - the CRD is now generated rather than hand-crafted, that's why it's differing.

Here is where it changed -> https://github.com/openfaas-incubator/ingress-operator/commit/1ce6cda629d9bca360de899e7bda4897d2a403cc
