### ISSUE TITLE
Allow users to choose the kind of isser (ClusterIssuer or Issuer)

### ISSUE THREAD

**Issue by matipan** [openfaas-incubator/ingress-operator#8]
We currently let the user choose the `kind` of cert-manager issuer, the two available options are `Issuer` and `ClusterIssuer`. However, we don't use the value of that field when we set the annotations.

## Expected Behaviour

I would expect that when I set the `kind` field inside `issuerRef` that change would be reflected on the ingress's annotations.

## Current Behaviour

We can set the `kind` field inside `issuerRef` but it's a no-op.

## Possible Solution

I see the following two options:
* Only allow the `issuer` kind and remove the `kind` field so that we are not misleading the user
* Use the value of `kind` to set the cert-manager's annotations

I've implemented the second one and test it out on my cluster. It works OK and it was a very simple change, but I don't know if this is what we want. Lets discuss 😄 

## Steps to Reproduce (for bugs)

1. Set the `kind` in `issuerRef` to `ClusterIssuer` and notice that the annotation continues to be for an `issuer`.

## Context

I was trying to create a new function ingress using the existing `ClusterIssuer` in my cluster, this issuer is created by ofc-bootstrap when installing ofc in the cluster.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* What version and distriubtion of Kubernetes are you using? `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

* Link to your project or a code example to reproduce issue:

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Calico on GKE

**Comment by matipan** [comment]
Derek add label: good first issue

**Comment by matipan** [comment]
Derek assign: me

**Comment by matipan** [comment]
Maybe we don't have derek here 😆

**Comment by affix** [comment]
I would also like this feature @matipan :)

**Comment by affix** [comment]
Derek close

**Comment by affix** [comment]
@alexellis we can close this now

**Comment by alexellis** [comment]
Let's change the file for a redirect to the faas repo? https://github.com/openfaas-incubator/ingress-operator/blob/master/.DEREK.yml

**Comment by alexellis** [comment]
Released in this version: https://github.com/openfaas-incubator/ingress-operator/releases/tag/0.3.1

**Comment by alexellis** [comment]
Thank you all
